import type { ContentEntry, ContentKind, SiteSettings } from "./types";

// Local preview content only. A configured database never falls back to these records.
function entry(kind: ContentKind, slug: string, title: string, summary: string, image: string, extra: Partial<ContentEntry> = {}): ContentEntry {
  return { id: slug, kind, slug, title, summary, body: summary, hero_image: image, image_alt: title, region: "South India", duration: "", tags: [], related_slugs: [], stops: [], published: true, seo_title: title, seo_description: summary, canonical_url: "", social_image: image, noindex: true, updated_at: "2026-10-01T00:00:00Z", ...extra };
}

export const demoContent: ContentEntry[] = [
  entry("destination", "tamil-nadu", "Tamil Nadu", "Chola temples & timeless traditions", "/images/thanjavur.jpg", { region: "Tamil Nadu", image_alt: "Brihadeeswarar Temple in Thanjavur at sunset", body: "Let the temple towns of Tamil Nadu inspire your next journey. From the stone courtyards of Thanjavur to the living traditions of Madurai, there is room for both discovery and quiet reflection.\n\nTell us which temples matter to you, the time you have, and the people traveling with you. Your inquiry is the starting point for a personal itinerary; visits and arrangements are confirmed with the team.", related_slugs: ["chola-heritage", "tamil-nadu-temple-journey"] }),
  entry("destination", "kerala", "Kerala", "Sacred spaces & serene backwaters", "/images/kerala.jpg", { region: "Kerala", image_alt: "Traditional houseboat on Kerala's palm-lined backwaters", body: "Follow a gentler rhythm through Kerala. Discover temple traditions, green landscapes, and quiet stretches of water, with time to enjoy the places between each stop.\n\nShare your interests and preferred pace to begin planning a journey that brings spiritual visits and time in nature together.", related_slugs: ["kerala-temples-and-backwaters", "kerala-temple-trail"] }),
  entry("destination", "karnataka", "Karnataka", "Temple heritage & stories in stone", "/images/hampi.jpg", { region: "Karnataka", image_alt: "Virupaksha Temple seen through a stone pavilion in Hampi", body: "Discover Karnataka through its temple architecture and cultural landscapes. Hampi invites you to linger among sculpted stone and wide horizons.\n\nLet us know the places you would like to explore and the support your group needs. We will discuss a route and pace that works for your trip.", related_slugs: ["karnataka-heritage", "karnataka-sacred-trail"] }),
  entry("journey", "tamil-nadu-temple-journey", "A journey through Chola country", "Trace the temple heritage of Thanjavur and the towns around it.", "/images/thanjavur.jpg", { region: "Tamil Nadu", tags: ["Temple heritage", "Culture"], related_slugs: ["tamil-nadu", "chola-heritage"], stops: ["Thanjavur", "Kumbakonam", "Darasuram"], body: "Begin with the places that move you. This journey idea brings the temple landscapes around Thanjavur into one thoughtfully paced route.\n\nShare your dates, group size, and places of interest. The team will help shape the sequence of visits, transport arrangements, and time for rest around your preferences. The route is a starting point for discussion and is confirmed after your inquiry." }),
  entry("journey", "kerala-temples-and-backwaters", "Temples & tranquil backwaters", "Make space for spiritual discovery and the slower rhythm of Kerala.", "/images/kerala.jpg", { region: "Kerala", tags: ["Nature", "Spiritual journey"], related_slugs: ["kerala", "kerala-temple-trail"], body: "Bring together the temple traditions and waterside landscapes of Kerala. Your interests set the balance between visits, local exploration, and time to unwind.\n\nTell us where you are arriving, how long you hope to stay, and who is coming along. We will discuss the practical details with you before confirming an itinerary." }),
  entry("journey", "karnataka-heritage", "Karnataka, carved in time", "Explore sacred architecture and the cultural landscapes of Hampi.", "/images/hampi.jpg", { region: "Karnataka", tags: ["Heritage", "Architecture"], related_slugs: ["karnataka", "karnataka-sacred-trail"], body: "Take time to look closer at Karnataka's temple heritage. This journey idea starts with Hampi and the places you would most like to understand.\n\nWhether you travel as a family or with a small group, share your preferred pace and interests. Your inquiry helps the team build a practical plan with time for exploration and rest." }),
  ...[
    ["chola-heritage", "Chola", "Temple circuit", "Tamil Nadu", "/images/thanjavur.jpg", "Thanjavur|Darasuram|Gangaikonda Cholapuram"],
    ["shiva-temple-circuit", "Shiva", "Temple circuit", "Tamil Nadu", "/images/thanjavur.jpg", "Share your preferred Shiva temples"],
    ["shakti-temple-circuit", "Shakti", "Temple circuit", "Tamil Nadu", "/images/thanjavur.jpg", "Share your preferred Shakti temples"],
    ["murugan-temple-circuit", "Murugan", "Temple circuit", "Tamil Nadu", "/images/thanjavur.jpg", "Share your preferred Murugan temples"],
    ["kerala-temple-trail", "Kerala", "Temple journey", "Kerala", "/images/kerala.jpg", "Plan your Kerala temple visits"],
    ["karnataka-sacred-trail", "Karnataka", "Sacred trail", "Karnataka", "/images/hampi.jpg", "Hampi|Discuss further stops with the team"],
  ].map(([slug, title, summary, region, image, stops]) => entry("circuit", slug, title, summary, image, { region, stops: stops.split("|"), body: `Explore a ${title} journey built around your spiritual interests. Share the temples you hope to visit and the time you have available.\n\nThe team will discuss the route, timing, and travel arrangements with you. All stops and services are confirmed during planning.`, related_slugs: [region.toLowerCase().replaceAll(" ", "-")] })),
  entry("service", "family-ceremonies", "Celebrate life's sacred milestones", "Bring your family together for meaningful moments rooted in tradition.", "/images/thanjavur.jpg", { tags: ["Family ceremonies", "Temple visits", "Travel coordination"], body: "Every family has traditions worth honoring. Tell us about the occasion you are planning, your preferred temple or location, and the family members joining you.\n\nDiscuss ceremony arrangements, temple visits, accommodation, and transport with the team. Specific services and permissions are confirmed as part of planning.", stops: ["Tell us about your occasion", "Discuss the temple and family requirements", "Review your personal travel plan"] }),
  entry("service", "senior-assistance", "Travel with comfort. Pray with peace.", "A thoughtful pace, time to rest, and the support that matters to your family.", "/images/kerala.jpg", { tags: ["Comfortable travel", "A gentler pace", "Personal planning"], body: "A meaningful journey should make room for comfort. Share your preferred pace, walking preferences, and practical assistance needs so the team can discuss suitable arrangements.\n\nTransport, accommodation, and temple access are reviewed during planning. Please discuss practical travel needs only; do not submit medical information through the inquiry form.", stops: ["Share your pace and travel preferences", "Discuss transport and assistance", "Plan time for visits and rest"] }),
  entry("service", "b2b-partners", "Meaningful journeys, built together", "Connect with Kalasam Tourism to discuss travel partnerships in South India.", "/images/hampi.jpg", { tags: ["Travel partners", "Group inquiries", "South India"], body: "We welcome conversations with travel professionals who want to help their guests experience South India's spiritual and cultural heritage.\n\nTell us about your organization, the travelers you serve, and the kind of partnership you have in mind. The team will follow up to discuss services and next steps.", stops: ["Introduce your organization", "Share your guests' interests", "Explore a partnership with our team"] }),
];

export const demoSettings: SiteSettings = {
  brand_name: "Kalasam Tourism", email: "", phone: "", whatsapp: "", address: "", instagram: "", facebook: "", privacy_text: "", consent_text: "", consent_version: "",
};
